### ISSUE TITLE
Support leading white-space with org-adapt-indentation

### ISSUE THREAD

**Issue by mohkale** [xenodium/company-org-block#1]
Hi, love the package.

I agree you'd probably only ever want org-block completions when at the beginning of a line but for those of us that have `org-adapt-indentation` set to `t`, this package won't offer to complete any lines that're in a sub-heading because the lines are indented to match the heading level. I'd suggest allowing `company-org-block-complete-at-bol` to disregard leading whitespace.

This diff fixes the issue for me:

```diff
--- /home/mohkale/.config/dotfiles/prog/editors/emacs/lisp/straight/repos/company-org-block/company-org-block.el
+++ #<buffer company-org-block.el>
@@ -106,10 +106,12 @@
 #+begin_BEGIN
   |
 #+end_END"
+  (org-indent-line)
   (insert (format "#+begin_%s\n" begin))
   (insert (make-string org-edit-src-content-indentation ?\s))
   (save-excursion
-    (insert (format "\n#+end_%s" end)))
+    (insert (format "\n#+end_%s" end))
+    (org-indent-line))
   (cond ((eq company-org-block-edit-style 'auto)
          (org-edit-special))
         ((and (eq company-org-block-edit-style 'prompt)
@@ -120,7 +122,7 @@
   "Return cons with symbol and t whenever prefix of < is found.
 For example: \"<e\" -> (\"e\" . t)"
   (when (looking-back (if company-org-block-complete-at-bol
-                          (concat "^" company-org-block--regexp)
+                          (concat "^[[:space:]]*" company-org-block--regexp)
                         company-org-block--regexp)
                       (line-beginning-position))
     (cons (match-string-no-properties 1) t)))
```

Also I'd like to ask whether there's a reason behind the lack of a trailing newline on the end_src? In my emacs not having one leads to the font-lock at that point getting cut off.
![Screenshot_20210606_180433](https://user-images.githubusercontent.com/23294780/120933417-fe40a700-c6f1-11eb-8bb1-18cd8517b23a.png)

**Comment by xenodium** [comment]
Thanks for the suggestions Mohsin. Both sound good to me. Want to send a PR?

edit: typo

**Comment by xenodium** [comment]
Thanks for raising and fixing Mohsin.

**Comment by mohkale** [comment]
@xenodium 

In retrospect the trailing linebreak after end_src was probably un-necessary. It makes sense at the end of a buffer... but most of the time you're probably higher up. Can we remove it?

**Comment by xenodium** [comment]
> Can we remove it?

lol sure!

Could you send a PR please?

**Comment by mohkale** [comment]
And done. Apologies for the inconvenience. :smile:

**Comment by xenodium** [comment]
No problem. Thanks for following up.
