### ISSUE TITLE
Indentation breaks if there's text below

### ISSUE THREAD

**Issue by xenodium** [xenodium/company-org-block#11]
![company-bug](https://user-images.githubusercontent.com/8107219/121807667-a8658500-cc44-11eb-9cc1-3c9a9ec4368e.gif)

**Comment by xenodium** [comment]
@takaxp @mohkale I've fixed this in d63fe9c. Please lemme know if your use-cases are not OK.

**Comment by takaxp** [comment]
I've confirmed the commit resolved the issue :)

**Comment by xenodium** [comment]
> I've confirmed the commit resolved the issue :)

Gracias :)
