### ISSUE TITLE
[Question] Completion suggests language's file extension

### ISSUE THREAD

**Issue by david-vicente** [xenodium/company-org-block#13]
Is there a reason why the completion is suggesting both the languages and their file extensions?

![image](https://user-images.githubusercontent.com/57544666/183703725-208276fa-fe85-4dee-9f39-30b38713702a.png)

The extensions are not valid headers for org blocks, so this is a bit annoying.

**Comment by david-vicente** [comment]
I can see that [this function](https://github.com/xenodium/company-org-block/blob/115af0a3625f4669358eca568466d468cacc78bd/company-org-block.el#L77) seems to get the candidates from multiple sources, and one of them is `company-org-block--languages-from-extensions`.

Maybe there is something wrong with this [function](https://github.com/xenodium/company-org-block/blob/115af0a3625f4669358eca568466d468cacc78bd/company-org-block.el#L108).

**Comment by xenodium** [comment]
Can you confirm the completion is coming from `company-org-block` and not another company backend? Cancel the suggestion with `C-g` and then explicitly invoke company-org-block`. Something like:

`<` `C-g` `M-x company-org-block`

**Comment by xenodium** [comment]
Ah nevermind, it was a bug in `company-org-block--languages-from-extensions` as you mentioned. Can you try the latest?

**Comment by david-vicente** [comment]
It seems to be working now. Thanks!

**Comment by david-vicente** [comment]
By the way, the GIFs in the README were created prior to this fix, so you can see the extensions in some of the GIFs. It is probably a small detail, but if you could record them again it would be nice.
